data:
  train_data_dir: "data"
  predict_data_dir: "data/opensource"
  prefix: "opensource"
  universe: "csi300"
  
model:
  d_feat: 158
  d_model: 256
  t_nhead: 4
  s_nhead: 2
  dropout: 0.5
  gate_input_start_index: 158
  gate_input_end_index: 221
  beta: 5
  
training:
  seeds: [0] #[0, 1, 2, 3, 4]
  n_epoch: 40
  lr: 0.00001
  gpu: 0
  train_stop_loss_thred: 0.95
  save_path: "model"

















